# Inventory file - defines the target hosts where Ansible will install components
# The VM IP is passed as a parameter from GitHub Actions pipeline

[nodes]
penina-node ansible_host={{ node_ip }} ansible_user=root ansible_ssh_private_key_file=~/.ssh/devops-exam

[nodes:vars]
ansible_python_interpreter=/usr/bin/python3